### ISSUE TITLE
 [feature request] Show the list of all logged in users

### ISSUE THREAD

**Issue by jaspreet-tenjin** [nafeu/beewomp#9] opened 2022-09-20 20:06 UTC

**Comment by amirmanji** [comment] 2022-09-20 20:09
this is a duplicate of #2

**Comment by jaspreet-tenjin** [comment] 2022-09-20 20:13
duplicate issue

**Closed** 2022-09-20 20:13 UTC

**Comment by matiasdominguez** [comment] 2022-09-20 20:28
I'm so happy to see the absolute seriousness with which we take beewomp's roadmap and development. Thanks community
